# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27e1b0f6dee3a2e817a1d333809245cf1d2fa9f5608a263dbc853aff6d49bc68238a53367ee09799434f774285251a4c64de995310139f2115952e4a8fb53082

test:
  secret_key_base: 4a8169e4cee8ef8342f3e3747d3b7f557f0497dc1dc0ac20c59354cef85aa8e526a4f7a5deef09d4d112e5a02f168715fdb0c9a91332433dbbe482e70d07bb8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
